# .github/workflows/build-gop.yml
name: Build GoPass for Linux AMD64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod tidy

    - name: Build application
      env:
        GOOS: linux
        GOARCH: amd64
      run: |
        mkdir -p release

        go build -v -o release/gopass ./cmd/server

        cp -r web release/

    - name: Create archive
      run: |
        cd release && tar -czvf ../gopass-linux-amd64.tar.gz .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gopass-linux-amd64
        path: gopass-linux-amd64.tar.gz
